### PR TITLE
Fix Solarized palette

### PR DESCRIPTION
**Pull request by jamjury**
All other default palettes make ${USER}@${HOSTNAME} green and ${PWD} blue, but with
Solarized everything is grey. I think, those colors should be somewhat consistent.
Swap normal and bright colors to fix it.

Screenshots:
Current Solarized palette
If applied, this commit will change it to following

Other palettes:
Tango
Linux console
XTerm

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to gnome-terminal!

gnome-terminal uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers
and follow the instructions there to upload your change to Bugzilla.

**Comment by egmontkob** [comment]
Solarized palette is defined on its homepage, the URL is even present in your patch. Please see the specs over there, compare with gnome-terminal's implementation, and let us know if you find any difference.

Solarized is _not_ a color scheme which keeps traditional green as green and traditional blue as blue. If that's what you expect, that's a false expectation, and you should probably stick to another color scheme.

**Comment by egmontkob** [comment]
Oh, by the way... upgrade to gnome-terminal 3.28 and disable the "Show bold text in bright colors" option on its color settings tab. Probably this is what confused you. This is indeed something that was missing from gnome-terminal for a long time, to get you real colors rather than gray ones.

**Comment by egmontkob** [comment]
I just realized that my first comment might have come across as a bit harsh, sorry in that case, I didn't mean that, I was simply quite tired yesterday.

Submitted https://git.gnome.org/browse/gnome-terminal/commit/?id=e8ee9f786to make it more obvious that we indeed define the Solarized palette correctly.

As per my second comment, the brand new "Show bold text in bright colors" option is probably what you're looking for.

**Pull request closed without merging**
